# Generated by Django 4.2.30 on 2026-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grant_daily_profit_nav_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('marketplaces', models.CharField(blank=True, help_text='Which platforms they sell on', max_length=200)),
                ('monthly_orders', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('DROPPED', 'Not interested')], db_index=True, default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='landing', max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
