# Generated by Django 4.2.30 on 2026-09-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_grant_return_analysis_nav_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pricing_groups",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="pricing_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="accounts.pricinggroup",
            ),
        ),
    ]
