# Generated by Django 4.2.30 on 2026-09-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_grant_flipkart_profit_nav_path'),
        ('accounts', '0013_pricing_group'),
    ]

    operations = [
    ]
