# Generated by Django 4.2.30 on 2026-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20260927_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='deduct_employee_salaries',
            field=models.BooleanField(default=False, help_text='Subtract employee salaries (incl. extra pay) from profit for this business'),
        ),
    ]
