services:
  - type: web
    name: meesho-p
    runtime: python
    rootDir: .
    buildCommand: |
      npm ci --prefix frontend
      npm run build --prefix frontend
      mkdir -p backend/templates
      cp backend/frontend_build/index.html backend/templates/index.html
      pip install -r backend/requirements.txt
      cd backend && python manage.py collectstatic --noinput
    startCommand: |
      cd backend && python manage.py migrate && gunicorn meesho_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL
        value: "true"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: "sqlite"
