# Generated by Django 4.2.30 on 2026-06-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdsCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deduction_duration", models.DateField(blank=True, null=True)),
                ("deduction_date", models.DateField(blank=True, null=True)),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ad_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "credits_waivers_discounts",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ad_cost_incl_credits_waivers",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_ads_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ads_cost",
                "ordering": ["-deduction_date"],
            },
        ),
        migrations.CreateModel(
            name="CompensationRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "program_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "amount_incl_gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compensation_recovery",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LabelOrder",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("customer_address", models.TextField(blank=True)),
                (
                    "customer_city",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "customer_pincode",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                (
                    "courier_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("awb_number", models.CharField(blank=True, max_length=100)),
                ("payment_type", models.CharField(blank=True, max_length=20)),
                ("pickup_date", models.CharField(blank=True, max_length=20)),
                ("sku", models.CharField(blank=True, max_length=300)),
                ("size", models.CharField(blank=True, max_length=100)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("uploaded_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "label_orders",
                "ordering": ["-uploaded_date", "courier_name"],
            },
        ),
        migrations.CreateModel(
            name="ParentItemPrice",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "item_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_percent", models.IntegerField(blank=True, null=True)),
                (
                    "packaging_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "parent_item_price",
                "ordering": ["item_id"],
            },
        ),
        migrations.CreateModel(
            name="ReferralPayment",
            fields=[
                (
                    "reward_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("store_name", models.CharField(blank=True, max_length=200, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "net_referral_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "taxes_gst_tds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "referral_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_order_no", models.CharField(db_index=True, max_length=100)),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                ("dispatch_date", models.DateField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                (
                    "supplier_sku",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("catalog_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "order_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "live_order_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_gst_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "listing_price_incl_taxes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "final_settlement_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("price_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "total_sale_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_sale_return_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fixed_fee_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "warehousing_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "return_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "return_premium_of_return",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "meesho_commission_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "meesho_commission_incl_gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "meesho_gold_platform_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "meesho_mall_platform_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fixed_fee_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "warehousing_fee_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "return_shipping_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst_compensation_prp_shipping",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "shipping_charge_incl_gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "other_support_service_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "waivers",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "net_other_support_service_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gst_on_net_other_support_service_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tds_rate_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "compensation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "claims",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "recovery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("compensation_reason", models.TextField(blank=True, null=True)),
                ("claims_reason", models.TextField(blank=True, null=True)),
                ("recovery_reason", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_payments",
                "ordering": ["-order_date"],
                "unique_together": {
                    ("sub_order_no", "payment_date", "live_order_status")
                },
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_for_credit_entry",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sub_order_no", models.CharField(db_index=True, max_length=100)),
                ("catalog_id", models.BigIntegerField(blank=True, null=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "order_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_name", models.TextField(blank=True, null=True)),
                ("sku", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "supplier_listed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "supplier_discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("packet_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-order_date"],
                "unique_together": {
                    ("sub_order_no", "reason_for_credit_entry", "order_date")
                },
            },
        ),
        migrations.CreateModel(
            name="FinalPrice",
            fields=[
                (
                    "sku_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "item_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_percent", models.IntegerField(blank=True, null=True)),
                (
                    "packaging_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_prices",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "final_price",
                "ordering": ["sku_id"],
            },
        ),
    ]
