# Generated by Django 4.2.30 on 2026-06-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0002_add_orders_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("seller_name", models.CharField(max_length=255)),
                ("bill_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "purchase_bills",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_description", models.CharField(blank=True, max_length=500)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_exchange", models.BooleanField(default=False)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meesho_app.purchasebill",
                    ),
                ),
                (
                    "parent_sku",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_sku_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_items",
            },
        ),
    ]
