# Generated by Django 4.2.30 on 2026-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0002_finalprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_for_credit_entry",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "Delivered"),
                            ("RTO_COMPLETE", "RTO Complete"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sub_order_no", models.CharField(max_length=100, unique=True)),
                ("catalog_id", models.BigIntegerField()),
                ("order_date", models.DateField()),
                (
                    "order_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customer_state", models.CharField(max_length=100)),
                ("product_name", models.TextField()),
                ("sku", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "supplier_listed_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "supplier_discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("packet_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-order_date"],
            },
        ),
    ]
