# Generated by Django 4.2.30 on 2026-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0003_purchase_and_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(db_index=True, max_length=255)),
                ("customer_pincode", models.CharField(db_index=True, max_length=10)),
                ("customer_city", models.CharField(blank=True, max_length=100)),
                ("customer_state", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "blocked_customers",
                "ordering": ["-blocked_at"],
                "unique_together": {("customer_name", "customer_pincode")},
            },
        ),
    ]
