# Generated by Django 4.2.30 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalprice",
            name="tax_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
