# Generated by Django 4.2.30 on 2026-06-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0004_alter_finalprice_tax_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentItemPrice",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "item_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_percent", models.IntegerField(blank=True, null=True)),
                (
                    "packaging_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "parent_item_price",
                "ordering": ["item_id"],
            },
        ),
        migrations.AddField(
            model_name="finalprice",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sku_prices",
                to="meesho_app.parentitemprice",
            ),
        ),
    ]
