# Generated by Django 4.2.30 on 2026-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0004_blocked_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelorder",
            name="is_packed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="labelorder",
            name="packed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
