# Generated by Django 4.2.30 on 2026-06-10 13:57

from django.db import migrations, models


def deduplicate_ads_cost(apps, schema_editor):
    """Keep only the latest row per (deduction_duration, deduction_date, campaign_id)."""
    AdsCost = apps.get_model("meesho_app", "AdsCost")
    seen = {}
    # Order by id so the highest id (most recent upload) wins
    for row in AdsCost.objects.order_by("id"):
        key = (row.deduction_duration, row.deduction_date, row.campaign_id)
        if key in seen:
            seen[key].delete()
        seen[key] = row


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0005_add_packing_to_labelorder"),
    ]

    operations = [
        migrations.RunPython(deduplicate_ads_cost, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="adscost",
            constraint=models.UniqueConstraint(
                fields=("deduction_duration", "deduction_date", "campaign_id"),
                name="unique_ads_cost_entry",
            ),
        ),
    ]
