# Generated by Django 4.2.30 on 2026-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0005_parentitemprice_finalprice_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelOrder",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_address", models.TextField(blank=True)),
                (
                    "customer_city",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("customer_pincode", models.CharField(blank=True, max_length=10)),
                (
                    "courier_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("awb_number", models.CharField(blank=True, max_length=100)),
                ("payment_type", models.CharField(blank=True, max_length=20)),
                ("pickup_date", models.CharField(blank=True, max_length=20)),
                ("sku", models.CharField(blank=True, max_length=300)),
                ("size", models.CharField(blank=True, max_length=100)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("uploaded_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "label_orders",
                "ordering": ["-uploaded_date", "courier_name"],
            },
        ),
    ]
