# Generated by Django 4.2.30 on 2026-06-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0006_ads_cost_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_percent", models.IntegerField(default=0)),
                (
                    "packaging_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        db_column="parent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "parent_price_history",
                "ordering": ["effective_from"],
                "unique_together": {("parent", "effective_from")},
            },
        ),
    ]
