# Generated by Django 4.2.30 on 2026-06-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0007_parent_price_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged / Written Off"),
                            ("FOUND", "Stock Found / Recount"),
                            ("CORRECTION", "Inventory Correction"),
                            ("LOST", "Lost / Stolen"),
                            ("RETURN", "Customer Return (non-Meesho)"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_sku",
                    models.ForeignKey(
                        db_column="parent_sku_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_adjustments",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_adjustments",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
