# Generated by Django 4.2.30 on 2026-06-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0008_inventory_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("POLYTHENE", "Polythene / Plastic Bags"),
                            ("BUBBLE_WRAP", "Bubble Wrap"),
                            ("STATIONARY", "Stationery"),
                            ("LABELS", "Shipping Labels / Tape"),
                            ("BOX", "Boxes / Packaging"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pieces", "Pieces"),
                            ("rolls", "Rolls"),
                            ("meters", "Meters"),
                            ("grams", "Grams"),
                            ("kgs", "Kilograms"),
                            ("packs", "Packs"),
                            ("boxes", "Boxes"),
                        ],
                        default="pieces",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "consumable_items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase Item"),
                            ("ADJUSTMENT", "Stock Adjustment"),
                            ("SKU", "Parent SKU"),
                            ("CONSUMABLE_PURCHASE", "Consumable Purchase"),
                            ("CONSUMABLE_USAGE", "Consumable Usage"),
                            ("CONSUMABLE_ITEM", "Consumable Item"),
                        ],
                        max_length=25,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "parent_sku_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("quantity_change", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent_sku_id", "-created_at"],
                        name="inventory_l_parent__2dec98_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "-created_at"],
                        name="inventory_l_entity__a053e9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsumableUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USE", "Used / Consumed"),
                            ("OPEN", "Opened New Package"),
                            ("WASTE", "Damaged / Wasted"),
                        ],
                        default="USE",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="meesho_app.consumableitem",
                    ),
                ),
            ],
            options={
                "db_table": "consumable_usages",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsumablePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("seller_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="meesho_app.consumableitem",
                    ),
                ),
            ],
            options={
                "db_table": "consumable_purchases",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
