# Generated by Django 4.2.30 on 2026-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0009_consumables_and_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeeshoInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.PositiveIntegerField(
                        help_text="Row identifier from the Meesho sheet", unique=True
                    ),
                ),
                ("catalog_name", models.CharField(max_length=500)),
                ("catalog_id", models.BigIntegerField(db_index=True)),
                ("product_name", models.TextField()),
                ("product_id", models.BigIntegerField(db_index=True)),
                ("style_id", models.CharField(blank=True, max_length=255)),
                ("variation_id", models.BigIntegerField(blank=True, null=True)),
                ("variation", models.CharField(blank=True, max_length=255)),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                            ("ALL", "All"),
                        ],
                        default="ALL",
                        max_length=15,
                    ),
                ),
                (
                    "system_stock_count",
                    models.IntegerField(
                        default=0, help_text="Current stock count as reported by Meesho"
                    ),
                ),
                (
                    "seller_stock_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Seller-edited stock count to push to Meesho",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meesho_inventory",
                "ordering": ["serial_no"],
                "indexes": [
                    models.Index(
                        fields=["catalog_id"], name="meesho_inve_catalog_a45cea_idx"
                    ),
                    models.Index(
                        fields=["product_id"], name="meesho_inve_product_c15a12_idx"
                    ),
                ],
            },
        ),
    ]
