# Generated by Django 4.2.30 on 2026-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0009_consumables_and_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeeshoStockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_identifier", models.CharField(blank=True, max_length=200)),
                ("catalog_name", models.CharField(blank=True, max_length=500)),
                ("catalog_id", models.CharField(db_index=True, max_length=100)),
                ("product_name", models.CharField(blank=True, max_length=500)),
                ("product_id", models.CharField(db_index=True, max_length=100)),
                ("product_style_id", models.CharField(blank=True, max_length=200)),
                ("variation_id", models.CharField(blank=True, max_length=200)),
                ("variation", models.CharField(blank=True, max_length=500)),
                (
                    "stock_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN_STOCK", "IN_STOCK"),
                            ("OUT_OF_STOCK", "OUT_OF_STOCK"),
                            ("ALL", "ALL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_stock", models.IntegerField(blank=True, null=True)),
                ("edit_stock", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meesho_stock_item",
                "ordering": ["catalog_id", "product_id"],
                "unique_together": {("catalog_id", "product_id")},
            },
        ),
    ]
