# Generated by Django 4.2.30 on 2026-06-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0010_meesho_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeeshoPriceUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_msp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New Meesho Selling Price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "new_wdrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wrong/Defective Return Price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "new_mrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New Maximum Retail Price (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_update",
                        to="meesho_app.meeshoinventory",
                    ),
                ),
            ],
            options={
                "db_table": "meesho_price_updates",
                "ordering": ["inventory__serial_no"],
            },
        ),
    ]
