# Generated by Django 4.2.30 on 2026-07-03 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0010_meesho_stock_item"),
        ("meesho_app", "0011_meesho_price_update"),
    ]

    operations = []
