# Generated by Django 4.2.30 on 2026-07-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("meesho_app", "0017_expenseinvoice_transportcharge_expenseinvoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase Item"),
                    ("ADJUSTMENT", "Stock Adjustment"),
                    ("SKU", "Parent SKU"),
                    ("CONSUMABLE_PURCHASE", "Consumable Purchase"),
                    ("CONSUMABLE_USAGE", "Consumable Usage"),
                    ("CONSUMABLE_ITEM", "Consumable Item"),
                    ("PACKED_STOCK", "Packed Stock Entry"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="PackedStockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("code_scanned", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.business",
                    ),
                ),
                (
                    "parent_sku",
                    models.ForeignKey(
                        db_column="parent_sku_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packed_stock_events",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "packed_stock_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
