# Generated by Django 4.2.30 on 2026-07-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("meesho_app", "0018_alter_inventorylog_entity_type_packedstockevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimatedProfitOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_order_no", models.CharField(db_index=True, max_length=100)),
                ("order_status", models.CharField(max_length=50)),
                ("catalog_id", models.CharField(blank=True, max_length=100, null=True)),
                ("sku_id", models.CharField(db_index=True, max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "payout_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payout_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "claim_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "db_table": "estimated_profit_orders",
                "ordering": ["-order_date", "-uploaded_at"],
                "unique_together": {("business", "sub_order_no", "order_status")},
            },
        ),
    ]
