# Generated by Django 4.2.30 on 2026-07-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_navvisibilitysetting'),
        ('meesho_app', '0019_estimatedprofitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suborder_no', models.CharField(db_index=True, max_length=100)),
                ('order_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('awb_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product_name', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=300)),
                ('variation', models.CharField(blank=True, max_length=255)),
                ('meesho_pid', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('return_created_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, db_index=True, null=True)),
                ('type_of_return', models.CharField(blank=True, max_length=60)),
                ('sub_type', models.CharField(blank=True, max_length=60)),
                ('courier_partner', models.CharField(blank=True, max_length=100)),
                ('tracking_link', models.TextField(blank=True)),
                ('proof_of_delivery', models.TextField(blank=True)),
                ('return_price_type', models.CharField(blank=True, max_length=100)),
                ('return_reason', models.TextField(blank=True)),
                ('detailed_return_reason', models.TextField(blank=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('claim_status', models.CharField(choices=[('UNREVIEWED', 'Not reviewed yet'), ('NOT_REQUIRED', 'No claim needed'), ('REQUIRED', 'Claim required'), ('RAISED', 'Claim raised'), ('APPROVED', 'Claim approved'), ('REJECTED', 'Claim rejected')], db_index=True, default='UNREVIEWED', max_length=20)),
                ('claim_marked_at', models.DateTimeField(blank=True, help_text='When the claim was flagged as required', null=True)),
                ('claim_raised_at', models.DateTimeField(blank=True, help_text='When the claim was actually raised on Meesho', null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claim_reference', models.CharField(blank=True, help_text='Meesho ticket / claim reference id', max_length=150)),
                ('claim_notes', models.TextField(blank=True)),
                ('verify_result', models.CharField(blank=True, choices=[('MATCH', 'Correct product received'), ('MISMATCH', 'Wrong product received')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'db_table': 'return_deliveries',
                'ordering': ['-delivered_date', '-return_created_date', '-uploaded_at'],
                'indexes': [models.Index(fields=['business', 'claim_status'], name='return_deli_busines_e6d965_idx'), models.Index(fields=['business', 'delivered_date'], name='return_deli_busines_a057af_idx')],
                'unique_together': {('business', 'suborder_no', 'awb_number')},
            },
        ),
    ]
