# Generated by Django 4.2.30 on 2026-07-31 07:16

from django.db import migrations, models

# Scope every remaining uniqueness rule to the owning business.
#
# The upload views already looked rows up with `business=business`, but the
# database keys omitted it — so a second business uploading its own Meesho
# exports hit "already exists" errors on identifiers that are only unique
# within one supplier account. Meesho numbers SERIAL NO from 1 in every
# export, which made the Meesho Stock upload fail outright for business #2
# with `UNIQUE constraint failed: meesho_inventory.serial_no`.


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_navvisibilitysetting'),
        ('meesho_app', '0020_returndelivery'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adscost',
            name='unique_ads_cost_entry',
        ),
        migrations.AlterField(
            model_name='meeshoinventory',
            name='serial_no',
            field=models.PositiveIntegerField(db_index=True, help_text='Row identifier from the Meesho sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='blockedcustomer',
            unique_together={('business', 'customer_name', 'customer_pincode')},
        ),
        migrations.AlterUniqueTogether(
            name='meeshoinventory',
            unique_together={('business', 'serial_no')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('business', 'sub_order_no', 'reason_for_credit_entry', 'order_date')},
        ),
        migrations.AlterUniqueTogether(
            name='orderpayment',
            unique_together={('business', 'sub_order_no', 'payment_date', 'live_order_status')},
        ),
        migrations.AddConstraint(
            model_name='adscost',
            constraint=models.UniqueConstraint(fields=('business', 'deduction_duration', 'deduction_date', 'campaign_id'), name='unique_ads_cost_entry'),
        ),
    ]
