# Generated by Django 4.2.30 on 2026-07-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_navvisibilitysetting'),
        ('meesho_app', '0021_scope_unique_keys_per_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Sale return / cancellation')], db_index=True, max_length=10)),
                ('financial_year', models.IntegerField(db_index=True)),
                ('month_number', models.IntegerField(db_index=True)),
                ('sub_order_num', models.CharField(db_index=True, max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('manifest_date', models.DateField(blank=True, null=True)),
                ('cancel_return_date', models.DateField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_taxable_sale_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_invoice_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('taxable_shipping', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('end_customer_state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('supplier_gstin', models.CharField(blank=True, max_length=20)),
                ('eco_tcs_gstin', models.CharField(blank=True, help_text="Meesho's GSTIN as the e-commerce operator", max_length=20)),
                ('supplier_id', models.CharField(blank=True, max_length=50)),
                ('sup_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'db_table': 'gst_transactions',
                'ordering': ['-financial_year', '-month_number', 'sub_order_num'],
                'indexes': [models.Index(fields=['business', 'financial_year', 'month_number', 'kind'], name='gst_transac_busines_a3239c_idx'), models.Index(fields=['business', 'gst_rate'], name='gst_transac_busines_2a8513_idx')],
            },
        ),
        migrations.CreateModel(
            name='GstInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, help_text='INVOICE / CREDIT NOTE / CREDIT_DISCOUNT / …', max_length=30)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('suborder_no', models.CharField(db_index=True, max_length=100)),
                ('product_description', models.TextField(blank=True)),
                ('hsn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('invoice_no', models.CharField(db_index=True, max_length=100)),
                ('period_year', models.IntegerField(db_index=True)),
                ('period_month', models.IntegerField(db_index=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
            ],
            options={
                'db_table': 'gst_invoice_details',
                'ordering': ['-order_date'],
                'unique_together': {('business', 'suborder_no', 'invoice_no')},
            },
        ),
    ]
