# Generated by Django 4.2.30 on 2026-08-04 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businessprofile_visible_paths_useraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meesho_app', '0022_gsttransaction_gstinvoicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_code', models.CharField(db_index=True, help_text='Exactly what the scanner read, before resolution', max_length=200)),
                ('sub_order_no', models.CharField(db_index=True, help_text='Resolved sub-order, or the raw code when unrecognised', max_length=100)),
                ('awb_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('matched_from', models.CharField(choices=[('LABEL', 'Shipping label'), ('PAYMENT', 'Payments sheet'), ('ORDER', 'Orders sheet'), ('NONE', 'Not recognised')], default='NONE', max_length=20)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=300)),
                ('product_name', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('courier_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_city', models.CharField(blank=True, max_length=100)),
                ('customer_state', models.CharField(blank=True, max_length=100)),
                ('customer_pincode', models.CharField(blank=True, max_length=10)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCANNED', 'Scanned'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('ON_HOLD', 'On hold'), ('ISSUE', 'Problem'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCANNED', max_length=20)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('scan_count', models.PositiveIntegerField(default=1)),
                ('first_scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_scanned_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scanned_orders',
                'ordering': ['-last_scanned_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='scanned_ord_busines_311120_idx'), models.Index(fields=['business', 'last_scanned_at'], name='scanned_ord_busines_2b898a_idx')],
                'unique_together': {('business', 'sub_order_no')},
            },
        ),
    ]
