# Generated by Django 4.2.30 on 2026-08-05 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businessprofile_visible_paths_useraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meesho_app', '0023_scannedorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('fields', models.JSONField(default=dict, help_text='logical field key → value to prefill')),
                ('labels', models.JSONField(blank=True, default=dict, help_text='logical field key → the label shown on the page')),
                ('source_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_templates', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['business', 'updated_at'], name='listing_tem_busines_3c5d08_idx')],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
