# Generated by Django 4.2.30 on 2026-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0024_listingtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedorder',
            name='ship_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannedorder',
            name='ship_status',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('NOT_SHIPPED', 'Not shipped yet'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'No status yet')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='scannedorder',
            name='ship_status_raw',
            field=models.CharField(blank=True, help_text='The sheet value this was derived from', max_length=100),
        ),
    ]
