# Generated by Django 4.2.30 on 2026-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0025_scannedorder_ship_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returndelivery',
            name='packet_check',
            field=models.CharField(blank=True, choices=[('MATCH', 'Packet matches what we shipped'), ('MISMATCH', 'Packet does not match'), ('UNKNOWN', 'Nothing on file to compare')], max_length=20),
        ),
        migrations.AddField(
            model_name='returndelivery',
            name='packet_id',
            field=models.CharField(blank=True, db_index=True, help_text='Packet / reverse-AWB scanned off the returned parcel', max_length=150),
        ),
        migrations.AddField(
            model_name='returndelivery',
            name='packet_matched_against',
            field=models.CharField(blank=True, help_text='The value it was compared with', max_length=150),
        ),
        migrations.AddField(
            model_name='returndelivery',
            name='packet_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
