# Generated by Django 4.2.30 on 2026-08-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grant_new_nav_paths'),
        ('meesho_app', '0026_returndelivery_packet_check_returndelivery_packet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=60)),
                ('suborder_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('order_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product_name', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=300)),
                ('variation', models.CharField(blank=True, max_length=255)),
                ('meesho_pid', models.CharField(blank=True, max_length=100)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OTHER', 'Other')], db_index=True, default='OPEN', max_length=20)),
                ('ticket_status_raw', models.CharField(blank=True, max_length=60)),
                ('issue', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at_meesho', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_update', models.TextField(blank=True)),
                ('reopen_validity', models.DateField(blank=True, null=True)),
                ('cpp_flag', models.CharField(blank=True, max_length=40)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('payment_state', models.CharField(choices=[('PAID', 'Paid'), ('SCHEDULED', 'Scheduled'), ('NONE', 'Not applicable')], db_index=True, default='NONE', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.business')),
                ('linked_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_tickets', to='meesho_app.returndelivery')),
            ],
            options={
                'db_table': 'claim_tickets',
                'ordering': ['-created_at_meesho', '-uploaded_at'],
                'indexes': [models.Index(fields=['business', 'ticket_status'], name='claim_ticke_busines_036141_idx'), models.Index(fields=['business', 'suborder_no'], name='claim_ticke_busines_9ae2bc_idx')],
                'unique_together': {('business', 'ticket_id')},
            },
        ),
    ]
