# Generated by Django 4.2.30 on 2026-08-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0027_claimticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedorder',
            name='ship_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
