
# Generated by Django 4.2.30 on 2026-08-06 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_grant_claims_nav_path'),
        ('meesho_app', '0028_scannedorder_ship_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('LISTING', 'Listing'), ('RETURN_CLAIM', 'Return claim')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('source_link', models.TextField(blank=True, help_text='Drive folder with the photo, or the claim video')),
                ('instructions', models.TextField(blank=True)),
                ('suborder_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, help_text='LISTING: paid on approval. RETURN_CLAIM: paid once the claim is up.', max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='RETURN_CLAIM: extra, paid if Meesho approves the claim', max_digits=10)),
                ('status', models.CharField(choices=[('ASSIGNED', 'To do'), ('SUBMITTED', 'Awaiting review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='ASSIGNED', max_length=20)),
                ('submitted_sku', models.CharField(blank=True, help_text='LISTING: the SKU id the worker created', max_length=300)),
                ('submitted_reference', models.CharField(blank=True, help_text='RETURN_CLAIM: ticket id / reference', max_length=200)),
                ('submitted_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_credited_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(blank=True, help_text='UPI / cash / bank transfer', max_length=60)),
                ('reference', models.CharField(blank=True, help_text='UTR or transaction note', max_length=150)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_settlements', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_settlements_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_settlements',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LISTING', 'Listing approved'), ('CLAIM_RAISED', 'Claim raised'), ('CLAIM_BONUS', 'Claim approved bonus'), ('ADJUSTMENT', 'Manual adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='INR. Positive is earned; adjustments may be negative.', max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries_created', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='meesho_app.walletsettlement')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='meesho_app.workertask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['business', 'status'], name='worker_task_busines_6253ad_idx'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['assigned_to', 'status'], name='worker_task_assigne_c18f81_idx'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['business', 'suborder_no'], name='worker_task_busines_92fd75_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['user', 'settlement'], name='wallet_entr_user_id_922f04_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['business', 'user'], name='wallet_entr_busines_404a85_idx'),
        ),
    ]
