# Generated by Django 4.2.30 on 2026-08-07 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_grant_tasks_nav_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meesho_app', '0029_workertask_walletsettlement_walletentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('MEESHO', 'Meesho'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart')], max_length=20)),
                ('task_type', models.CharField(choices=[('LISTING', 'Listing'), ('RETURN_CLAIM', 'Return claim')], default='LISTING', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='Claim tasks only', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_rates',
                'ordering': ['platform', 'task_type'],
            },
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_documents',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(db_index=True, max_length=300)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price on the platform', max_digits=12, null=True)),
                ('wrong_defective_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price claimed back for a wrong/defective return', max_digits=12, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_settlement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest settlement worth accepting', max_digits=12, null=True)),
                ('sku_prefix', models.CharField(blank=True, help_text='The agreed prefix this SKU should start with', max_length=100)),
                ('hsn_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workertask',
            name='worker_task_assigne_c18f81_idx',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workertask',
            name='assignees',
            field=models.ManyToManyField(related_name='worker_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workertask',
            name='is_paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workertask',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workertask',
            name='platform',
            field=models.CharField(choices=[('MEESHO', 'Meesho'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart')], db_index=True, default='MEESHO', max_length=20),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_listings', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_listings_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='meesho_app.workertask'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_documents', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='taskdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformrate',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_rates', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='platformrate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_rates_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='meesho_app.tasklisting'),
        ),
        migrations.AddIndex(
            model_name='tasklisting',
            index=models.Index(fields=['task', 'status'], name='task_listin_task_id_398903_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklisting',
            index=models.Index(fields=['created_by', 'status'], name='task_listin_created_531758_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasklisting',
            unique_together={('business', 'sku_id')},
        ),
        migrations.AlterUniqueTogether(
            name='platformrate',
            unique_together={('business', 'platform', 'task_type')},
        ),
    ]
