# Generated by Django 4.2.30 on 2026-08-07 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meesho_app', '0030_platformrate_taskdocument_tasklisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertask',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
