# Generated by Django 4.2.30 on 2026-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0031_workertask_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertask',
            name='listing_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
