# Generated by Django 4.2.30 on 2026-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0032_workertask_listing_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklisting',
            name='added_to_catalog_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
