# Generated by Django 4.2.30 on 2026-08-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meesho_app", "0033_tasklisting_added_to_catalog_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="platformrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="platformrate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_rates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workertask",
            name="listing_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_tasks",
                to="meesho_app.listingtemplate",
            ),
        ),
        migrations.AddField(
            model_name="workertask",
            name="parent_sku",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_sku_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_tasks",
                to="meesho_app.parentitemprice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformrate",
            unique_together={("business", "platform", "task_type", "user")},
        ),
    ]
