# Generated by Django 4.2.30 on 2026-08-11 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meesho_app", "0034_task_parent_template_user_rates"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkListingFieldPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("source_label", models.CharField(blank=True, max_length=255)),
                (
                    "fields",
                    models.JSONField(
                        default=dict, help_text="field key -> value to prefill"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="field key -> the human label shown at save time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_listing_presets",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_listing_presets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bulk_listing_field_presets",
                "ordering": ["name"],
                "unique_together": {("business", "name")},
            },
        ),
    ]
