# Generated by Django 4.2.30 on 2026-08-09 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meesho_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_lead'),
        ('meesho_app', '0034_task_parent_template_user_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCostSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_statuses', models.JSONField(default=meesho_app.models._default_packaging_statuses, help_text='Order outcomes whose packaging cost is deducted from profit.')),
                ('exchange_uses_two_packets', models.BooleanField(default=True)),
                ('sale_price_includes_gst', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_setting', to='accounts.business')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_cost_settings',
            },
        ),
    ]
