# Generated by Django 4.2.30 on 2026-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0035_businesscostsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalprice',
            name='parent_opt_out',
            field=models.BooleanField(default=False, help_text='Deliberately has no parent — hide it from linking and suggestions.'),
        ),
    ]
