# Generated by Django 4.2.30 on 2026-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0038_flipkartbulktemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseinvoiceitem",
            name="gst_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
