# Generated by Django 4.2.30 on 2026-08-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meesho_app", "0039_expenseinvoiceitem_gst_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_leaving", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("fixed_monthly", "Fixed Monthly"),
                            ("piecework", "Piecework"),
                            ("daily_wage", "Daily Wage"),
                            ("other", "Other"),
                        ],
                        default="fixed_monthly",
                        max_length=20,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                ("ifsc_code", models.CharField(blank=True, max_length=15)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                ("ifsc_code", models.CharField(blank=True, max_length=15)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                (
                    "ownership_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owners",
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "db_table": "business_owners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_on", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("advance", "Advance"),
                            ("bonus", "Bonus"),
                            ("reimbursement", "Reimbursement"),
                            ("other", "Other"),
                        ],
                        default="salary",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="UTR, cheque no., or transaction id",
                        max_length=150,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_payments",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="meesho_app.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_payments",
                "ordering": ["-paid_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "employee"],
                        name="employee_pa_busines_7353b9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["business", "status"], name="employees_busines_2907d1_idx"
            ),
        ),
    ]
