# Generated by Django 4.2.30 on 2026-08-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0010_grant_employees_nav_path"),
        ("meesho_app", "0040_employee_employeepayment_businessowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkListingBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("meesho", "Meesho"), ("flipkart", "Flipkart")],
                        max_length=20,
                    ),
                ),
                ("category_label", models.CharField(blank=True, max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("file_data", models.BinaryField()),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("FILE", "Uploaded file"),
                            ("BUILT_IN", "Built-in"),
                            ("TEMPLATE", "Saved template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_built_in_key", models.CharField(blank=True, max_length=100)),
                ("source_file_data", models.BinaryField(blank=True, null=True)),
                (
                    "source_original_filename",
                    models.CharField(blank=True, max_length=255),
                ),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                ("first_sku_id", models.CharField(db_index=True, max_length=300)),
                ("sku_ids", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bulk_listing_batches",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_listing_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_listing_batches",
                        to="meesho_app.flipkartbulktemplate",
                    ),
                ),
                (
                    "worker_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_listing_batches",
                        to="meesho_app.workertask",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_listing_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tasklisting",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_listings",
                to="meesho_app.bulklistingbatch",
            ),
        ),
    ]
