# Generated by Django 4.2.30 on 2026-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0043_product_photo_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="workertask",
            name="return_packet_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The packet id / reverse-AWB off the returned parcel, if known",
                max_length=150,
            ),
        ),
    ]
