# Generated by Django 4.2.30 on 2026-08-21 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_grant_bulk_labels_nav_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meesho_app", "0044_return_packet_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnVideoBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("MEESHO", "Meesho"),
                            ("AMAZON", "Amazon"),
                            ("FLIPKART", "Flipkart"),
                        ],
                        default="MEESHO",
                        max_length=20,
                    ),
                ),
                ("drive_link", models.URLField(max_length=2000)),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text='e.g. "Week 34 returns"', max_length=255
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Closed once fully worked through"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_video_batches",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_video_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "return_video_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="drive_link",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name="ProductPhoto",
        ),
        migrations.AddField(
            model_name="workertask",
            name="video_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="meesho_app.returnvideobatch",
            ),
        ),
    ]
