# Generated by Django 4.2.30 on 2026-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0047_labeldayreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentitemprice",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
