# Generated by Django 4.2.30 on 2026-09-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0047_flipkartorderpayment'),
        ('meesho_app', '0047_labeldayreset'),
    ]

    operations = [
    ]
