# Generated by Django 4.2.30 on 2026-09-26 18:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_grant_flipkart_profit_nav_path'),
        ('meesho_app', '0048_merge_0047_flipkartorderpayment_0047_labeldayreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gross salary for a full month. Day rate is derived from this.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_leave_per_month',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Leave days per month that are still paid. Leave beyond this is deducted.', max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_off_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Recurring weekly holiday for this employee (paid, not deducted).', null=True),
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='salary_month',
            field=models.DateField(blank=True, db_index=True, help_text='First day of the month this payment settles (salary/advance only).', null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('absent', 'Absent')], default='present', max_length=15)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('extra_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_attendance', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meesho_app.employee')),
            ],
            options={
                'db_table': 'employee_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_holidays', to='accounts.business')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='meesho_app.employee')),
            ],
            options={
                'db_table': 'employee_holidays',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['business', 'date'], name='employee_ho_busines_a3cd97_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeholiday',
            constraint=models.UniqueConstraint(fields=('business', 'employee', 'date'), name='uniq_holiday_emp_date'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['business', 'date'], name='employee_at_busines_4d3bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['employee', 'date'], name='employee_at_employe_3283f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_emp_date'),
        ),
    ]
