# Generated by Django 4.2.30 on 2026-10-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_pricing_group"),
        ("meesho_app", "0048_parentitemprice_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="master_items",
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "db_table": "master_item",
                "ordering": ["name"],
                "unique_together": {("business", "name")},
            },
        ),
        migrations.CreateModel(
            name="MasterItemComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "master_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in",
                        to="meesho_app.masteritem",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_components",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "master_item_component",
                "ordering": ["id"],
                "unique_together": {("parent", "master_item")},
            },
        ),
    ]
