# Generated by Django 4.2.30 on 2026-09-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0048_parentitemprice_image_url'),
        ('meesho_app', '0049_employee_monthly_salary_and_more'),
    ]

    operations = [
    ]
