# Generated by Django 4.2.30 on 2026-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0049_master_pricing_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="masteritem",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
