# Generated by Django 4.2.30 on 2026-10-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0050_masteritem_image_url'),
        ('meesho_app', '0050_merge_20260927_2224'),
    ]

    operations = [
    ]
