# Generated by Django 4.2.30 on 2026-10-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0051_merge_master_pricing_and_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="meesho_app.masteritem",
                    ),
                ),
            ],
            options={
                "db_table": "master_item_price_history",
                "ordering": ["effective_from"],
                "unique_together": {("master_item", "effective_from")},
            },
        ),
    ]
