# Generated by Django 4.2.30 on 2026-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meesho_app', '0052_master_item_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='extra_pay_reason',
            field=models.CharField(blank=True, choices=[('sunday', 'Sunday / weekly-off working'), ('holiday', 'Holiday working'), ('overtime', 'Overtime'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
