# Generated by Django 4.2.30 on 2026-10-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_businessprofile_deduct_employee_salaries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meesho_app", "0053_employeeattendance_extra_pay_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImageCounter",
            fields=[
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="listing_image_counter",
                        serialize=False,
                        to="accounts.business",
                    ),
                ),
                ("last_no", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "listing_image_counters",
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_no", models.PositiveIntegerField()),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("content_type", models.CharField(max_length=100)),
                ("bytes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending upload"),
                            ("uploaded", "Uploaded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listing_images",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_images_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_images",
                        to="meesho_app.parentitemprice",
                    ),
                ),
            ],
            options={
                "db_table": "listing_images",
                "ordering": ["-image_no"],
                "indexes": [
                    models.Index(
                        fields=["business", "sha256"],
                        name="listing_ima_busines_b4a1b2_idx",
                    )
                ],
                "unique_together": {("business", "image_no")},
            },
        ),
    ]
