# Generated by Django 4.2.30 on 2026-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meesho_app", "0054_listing_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingimage",
            name="folder",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
