from django.urls import path
from . import views
from . import bulk_listing_views

urlpatterns = [
    path("upload/", views.upload_excel, name="upload_excel"),
    path("profit/available-months/", views.available_months, name="available_months"),
    path("profit/daily/", views.profit_daily_summary, name="profit_daily_summary"),
    path("profit/", views.profit_summary, name="profit_summary"),
    path("estimated-profit/", views.estimated_profit_summary, name="estimated_profit_summary"),
    path("estimated-profit/upload/", views.estimated_profit_upload, name="estimated_profit_upload"),
    path("orders/", views.order_payments_list, name="order_payments_list"),
    path("orders/grouped/",          views.orders_grouped,         name="orders_grouped"),
    path("orders/status-breakdown/", views.order_status_breakdown, name="order_status_breakdown"),
    path("orders/unsettled/",       views.unsettled_orders,    name="unsettled_orders"),
    path("orders/unscheduled/",     views.unscheduled_payments, name="unscheduled_payments"),
    path("orders/payment-mismatch/", views.payment_mismatch,     name="payment_mismatch"),
    path("orders/return-claims/",    views.return_claims_detail, name="return_claims_detail"),
    path("orders/claimed/",          views.claimed_orders,        name="claimed_orders"),
    path("orders/breached/",         views.breached_orders_list,   name="breached_orders_list"),
    path("orders/breached/export/",  views.breached_orders_export, name="breached_orders_export"),
    path("ads/", views.ads_cost_list, name="ads_cost_list"),
    path("ads/sku-analysis/", views.ads_sku_analysis, name="ads_sku_analysis"),
    path("referrals/", views.referral_list, name="referral_list"),
    path("compensation/", views.compensation_recovery_list, name="compensation_recovery_list"),
    path("parent-prices/", views.parent_price_list, name="parent_price_list"),
    path("parent-prices/<str:item_id>/", views.parent_price_detail, name="parent_item_pricing"),
    path("parent-prices/<str:item_id>/price-history/", views.parent_price_history_list, name="parent_price_history_list"),
    path("parent-prices/<str:item_id>/price-history/<int:pk>/", views.parent_price_history_detail, name="parent_price_history_detail"),
    path("final-prices/unlinked/", views.unlinked_skus, name="unlinked_skus"),
    path("final-prices/unpriced/", views.unpriced_skus, name="unpriced_skus"),
    path("parent-prices/<str:item_id>/children/", views.parent_price_children, name="parent_price_children"),
    path("parent-prices/<str:item_id>/suggestions/", views.parent_sku_suggestions, name="parent_sku_suggestions"),
    path("parent-prices/<str:item_id>/price-sheet/", views.parent_price_sheet, name="parent_price_sheet"),
    path("sku-opt-out/", views.sku_parent_opt_out, name="sku_parent_opt_out"),
    path("link-sku/", views.link_sku_to_parent, name="link_sku_to_parent"),
    path("link-sku/bulk/", views.bulk_link_skus_to_parent, name="bulk_link_skus_to_parent"),
    path("parent-from-sku/", views.create_parent_from_sku, name="create_parent_from_sku"),
    path("parent-linking/", views.parent_linking_to_sku, name="parent_linking"),
    path("final-prices/", views.final_price_list, name="final_price_list"),
    path("final-prices/upload/", views.upload_final_price, name="upload_final_price"),
    path("final-prices/download/", views.download_final_price, name="download_final_price"),
    path("tax-check/", views.tax_check, name="tax_check"),
    path("pricing/download/", views.download_pricing_workbook, name="download_pricing_workbook"),
    path("pricing/upload/", views.upload_pricing_workbook, name="upload_pricing_workbook"),
    path("final-prices/<str:sku_id>/", views.final_price_detail, name="final_price_detail"),
    path("upload-orders/", views.upload_orders_csv, name="upload_orders"),
    path("full-orders/", views.full_orders_list, name="full_orders_list"),
    path("full-orders/analytics/", views.full_orders_analytics, name="full_orders_analytics"),
    path("dashboard/", views.dashboard_analytics, name="dashboard_analytics"),
    path("labels/parse/",            views.upload_labels_pdf,         name="upload_labels_pdf"),
    path("bulk-labels/parse/",       views.upload_bulk_labels_pdf,    name="upload_bulk_labels_pdf"),
    path("bulk-labels/extract/",     views.extract_label_pages,       name="extract_label_pages"),
    path("labels/orders/",           views.label_orders_list,         name="label_orders_list"),
    path("labels/summary/",          views.label_couriers_summary,    name="label_couriers_summary"),
    path("labels/duplicates/",       views.label_duplicate_customers, name="label_duplicate_customers"),
    path("labels/customer-history/", views.label_customer_history,    name="label_customer_history"),
    path("labels/customers/",        views.label_customers,           name="label_customers"),
    # Fraud & Blocked Customers
    path("fraud-customers/",                  views.fraud_customers,          name="fraud_customers"),
    path("blocked-customers/",                views.blocked_customers_list,   name="blocked_customers_list"),
    path("blocked-customers/<int:bc_id>/",    views.blocked_customer_detail,  name="blocked_customer_detail"),
    # Purchases & Inventory
    path("purchases/",              views.purchases_list,      name="purchases_list"),
    path("purchases/<int:bill_id>/",     views.purchase_detail, name="purchase_detail"),
    path("purchases/<int:bill_id>/pdf/", views.purchase_pdf,    name="purchase_pdf"),
    path("purchases/sku-items/",    views.purchase_sku_items,   name="purchase_sku_items"),
    path("purchases/sku-monthly/",  views.purchase_sku_monthly, name="purchase_sku_monthly"),
    path("purchases/items/<int:item_id>/", views.purchase_item_detail, name="purchase_item_detail"),
    path("inventory/",              views.inventory_view,           name="inventory_view"),
    path("inventory/new-sku/",      views.inventory_create_sku,     name="inventory_create_sku"),
    path("inventory/charts/",       views.inventory_charts,          name="inventory_charts"),
    path("inventory/logs/",         views.inventory_logs_list,       name="inventory_logs_list"),
    path("inventory/adjustments/",  views.inventory_adjustment_list, name="inventory_adjustment_list"),
    path("inventory/adjustments/<int:adj_id>/", views.inventory_adjustment_detail, name="inventory_adjustment_detail"),
    path("inventory/labels/",       views.inventory_labels_list,     name="inventory_labels_list"),
    path("inventory/packed/",       views.packed_stock_list,         name="packed_stock_list"),
    path("inventory/packed/<int:event_id>/", views.packed_stock_detail, name="packed_stock_detail"),
    path("inventory/<str:sku_id>/", views.inventory_delete_sku,      name="inventory_delete_sku"),
    path("consumables/items/",          views.consumable_items_list,       name="consumable_items_list"),
    path("consumables/items/<int:item_id>/", views.consumable_item_detail, name="consumable_item_detail"),
    path("consumables/purchases/",      views.consumable_purchases_list,   name="consumable_purchases_list"),
    path("consumables/purchases/<int:purchase_id>/", views.consumable_purchase_detail, name="consumable_purchase_detail"),
    path("consumables/usages/",         views.consumable_usages_list,      name="consumable_usages_list"),
    path("consumables/usages/<int:usage_id>/", views.consumable_usage_detail, name="consumable_usage_detail"),
    # Expenses: invoices (packaging / other) + daily transport charges
    path("expenses/invoices/",              views.expense_invoices_list,  name="expense_invoices_list"),
    path("expenses/invoices/<int:invoice_id>/", views.expense_invoice_detail, name="expense_invoice_detail"),
    path("expenses/transport/",             views.transport_charges_list, name="transport_charges_list"),
    path("expenses/transport/<int:charge_id>/", views.transport_charge_detail, name="transport_charge_detail"),
    path("expenses/summary/",               views.expenses_summary,       name="expenses_summary"),
    path("expenses/export/",                views.expenses_export,        name="expenses_export"),
    path("expenses/import/",                views.expenses_import,        name="expenses_import"),
    # Employee directory + owner details
    path("employees/",                        views.employees_list,           name="employees_list"),
    path("employees/summary/",                views.employees_summary,        name="employees_summary"),
    path("employees/<int:employee_id>/",      views.employee_detail,          name="employee_detail"),
    path("employees/<int:employee_id>/payments/", views.employee_payments_list, name="employee_payments_list"),
    path("employees/payments/<int:payment_id>/",  views.employee_payment_detail, name="employee_payment_detail"),
    path("owners/",              views.owners_list,  name="owners_list"),
    path("owners/<int:owner_id>/", views.owner_detail, name="owner_detail"),
    # Product Photography AI
    path("product-photos/generate/", views.generate_product_images, name="generate_product_images"),
    # Meesho Inventory
    path("meesho-inventory/",          views.meesho_inventory_list,     name="meesho_inventory_list"),
    path("meesho-inventory/upload/",   views.meesho_inventory_upload,   name="meesho_inventory_upload"),
    path("meesho-inventory/download/", views.meesho_inventory_download, name="meesho_inventory_download"),
    # Meesho Price Update
    path("meesho-price-update/",          views.meesho_price_update_list,     name="meesho_price_update_list"),
    path("meesho-price-update/download/", views.meesho_price_update_download, name="meesho_price_update_download"),
    # Return deliveries (returns received back) + 7-day claim tracking
    path("returns/",                    views.return_deliveries_list,   name="return_deliveries_list"),
    path("returns/upload/",             views.return_deliveries_upload, name="return_deliveries_upload"),
    path("returns/lookup/",             views.return_delivery_lookup,   name="return_delivery_lookup"),
    path("returns/<int:pk>/",           views.return_delivery_detail,   name="return_delivery_detail"),
    # Order scanning — log outgoing parcels at the desk and track their status
    path("order-scan/",              views.scanned_orders_list,        name="scanned_orders_list"),
    path("order-scan/bulk-status/",  views.scanned_orders_bulk_status, name="scanned_orders_bulk_status"),
    path("order-scan/refresh-ship/", views.scanned_orders_refresh_ship, name="scanned_orders_refresh_ship"),
    path("order-scan/<int:pk>/",     views.scanned_order_detail,       name="scanned_order_detail"),
    # Worker tasks + wallet
    path("worker-tasks/",              views.worker_tasks_list,   name="worker_tasks_list"),
    path("worker-tasks/workers/",      views.worker_list,         name="worker_list"),
    path("worker-tasks/<int:pk>/",     views.worker_task_detail,  name="worker_task_detail"),
    path("worker-tasks/<int:pk>/submit/", views.worker_task_submit, name="worker_task_submit"),
    path("worker-tasks/<int:pk>/review/", views.worker_task_review, name="worker_task_review"),
    path("task-listings/<int:pk>/",         views.task_listing_detail, name="task_listing_detail"),
    path("task-listings/<int:pk>/review/",  views.task_listing_review, name="task_listing_review"),
    path("task-reference/",   views.listing_reference,    name="listing_reference"),
    path("platform-rates/",   views.platform_rates,       name="platform_rates"),
    path("task-documents/",   views.task_documents,       name="task_documents"),
    path("task-documents/<int:pk>/", views.task_document_detail, name="task_document_detail"),
    path("wallet/",        views.wallet_summary, name="wallet_summary"),
    path("wallet/settle/", views.wallet_settle,  name="wallet_settle"),
    path("wallet/adjust/", views.wallet_adjust,  name="wallet_adjust"),
    # Claim tickets — the Meesho supplier-panel ticket export
    path("claims/",         views.claim_tickets_list,   name="claim_tickets_list"),
    path("claims/upload/",  views.claim_tickets_upload, name="claim_tickets_upload"),
    path("claims/relink/",  views.claim_tickets_relink, name="claim_tickets_relink"),
    # Listing templates — synced from the Meesho browser extension
    path("listing-templates/",         views.listing_templates_list,   name="listing_templates_list"),
    path("listing-templates/import/",  views.listing_templates_import, name="listing_templates_import"),
    path("listing-templates/export/",  views.listing_templates_export, name="listing_templates_export"),
    path("listing-templates/<int:pk>/", views.listing_template_detail, name="listing_template_detail"),
    # Bulk listing sheet generator — parses whatever Meesho category template
    # it's given (upload or a bundled built-in) and fills it in
    path("bulk-listing/built-ins/",
         bulk_listing_views.bulk_listing_built_ins, name="bulk_listing_built_ins"),
    path("bulk-listing/parse/",
         bulk_listing_views.bulk_listing_parse, name="bulk_listing_parse"),
    path("bulk-listing/generate/",
         bulk_listing_views.bulk_listing_generate, name="bulk_listing_generate"),
    path("bulk-listing/presets/",
         bulk_listing_views.bulk_listing_presets, name="bulk_listing_presets"),
    path("bulk-listing/presets/<int:pk>/",
         bulk_listing_views.bulk_listing_preset_detail, name="bulk_listing_preset_detail"),
    path("bulk-listing/flipkart-templates/",
         bulk_listing_views.bulk_listing_flipkart_templates, name="bulk_listing_flipkart_templates"),
    path("bulk-listing/flipkart-templates/<int:pk>/",
         bulk_listing_views.bulk_listing_flipkart_template_detail, name="bulk_listing_flipkart_template_detail"),
    path("bulk-listing/batches/",
         bulk_listing_views.bulk_listing_batches, name="bulk_listing_batches"),
    path("bulk-listing/batches/<int:pk>/",
         bulk_listing_views.bulk_listing_batch_detail, name="bulk_listing_batch_detail"),
    path("bulk-listing/batches/<int:pk>/download/",
         bulk_listing_views.bulk_listing_batch_download, name="bulk_listing_batch_download"),
    path("bulk-listing/batches/unlinked/",
         bulk_listing_views.bulk_listing_unlinked_batches, name="bulk_listing_unlinked_batches"),
    # Products — Team Tasks' central object (see models.Product)
    path("products/",                      views.products_list,        name="products_list"),
    path("products/<int:pk>/",             views.product_detail,       name="product_detail"),
    path("products/<int:pk>/photos/",      views.product_photos_add,   name="product_photos_add"),
    path("products/<int:pk>/link-batch/",  views.product_link_batch,   name="product_link_batch"),
    path("products/photos/<int:photo_id>/",       views.product_photo_delete, name="product_photo_delete"),
    path("products/<int:pk>/listings/",    views.product_listings,     name="product_listings"),
    path("legacy-listings/",               views.legacy_listings,      name="legacy_listings"),
    # GST — monthly liability from Meesho TCS exports
    path("gst/upload/",      views.gst_upload,      name="gst_upload"),
    path("gst/periods/",     views.gst_periods,     name="gst_periods"),
    path("gst/summary/",     views.gst_summary,     name="gst_summary"),
    path("gst/mismatches/",  views.gst_mismatches,  name="gst_mismatches"),
    # Label packing
    path("labels/orders/<str:order_id>/pack/", views.label_order_pack, name="label_order_pack"),
    path("labels/bulk-pack/",       views.label_bulk_pack,     name="label_bulk_pack"),
    path("labels/unpacked/",        views.label_unpacked,      name="label_unpacked"),
    # Business cost policy (packaging deductions, GST basis)
    path("cost-settings/", views.cost_settings, name="cost_settings"),
]
