from django.urls import path
from . import views

urlpatterns = [
    path("upload/", views.upload_excel, name="upload_excel"),
    path("profit/available-months/", views.available_months, name="available_months"),
    path("profit/", views.profit_summary, name="profit_summary"),
    path("estimated-profit/", views.estimated_profit_summary, name="estimated_profit_summary"),
    path("estimated-profit/upload/", views.estimated_profit_upload, name="estimated_profit_upload"),
    path("orders/", views.order_payments_list, name="order_payments_list"),
    path("orders/grouped/",          views.orders_grouped,         name="orders_grouped"),
    path("orders/status-breakdown/", views.order_status_breakdown, name="order_status_breakdown"),
    path("orders/unsettled/",       views.unsettled_orders,    name="unsettled_orders"),
    path("orders/unscheduled/",     views.unscheduled_payments, name="unscheduled_payments"),
    path("orders/payment-mismatch/", views.payment_mismatch,     name="payment_mismatch"),
    path("orders/return-claims/",    views.return_claims_detail, name="return_claims_detail"),
    path("orders/claimed/",          views.claimed_orders,        name="claimed_orders"),
    path("ads/", views.ads_cost_list, name="ads_cost_list"),
    path("ads/sku-analysis/", views.ads_sku_analysis, name="ads_sku_analysis"),
    path("referrals/", views.referral_list, name="referral_list"),
    path("compensation/", views.compensation_recovery_list, name="compensation_recovery_list"),
    path("parent-prices/", views.parent_price_list, name="parent_price_list"),
    path("parent-prices/<str:item_id>/", views.parent_price_detail, name="parent_item_pricing"),
    path("parent-prices/<str:item_id>/price-history/", views.parent_price_history_list, name="parent_price_history_list"),
    path("parent-prices/<str:item_id>/price-history/<int:pk>/", views.parent_price_history_detail, name="parent_price_history_detail"),
    path("final-prices/unlinked/", views.unlinked_skus, name="unlinked_skus"),
    path("link-sku/", views.link_sku_to_parent, name="link_sku_to_parent"),
    path("link-sku/bulk/", views.bulk_link_skus_to_parent, name="bulk_link_skus_to_parent"),
    path("parent-from-sku/", views.create_parent_from_sku, name="create_parent_from_sku"),
    path("parent-linking/", views.parent_linking_to_sku, name="parent_linking"),
    path("final-prices/", views.final_price_list, name="final_price_list"),
    path("final-prices/upload/", views.upload_final_price, name="upload_final_price"),
    path("final-prices/download/", views.download_final_price, name="download_final_price"),
    path("tax-check/", views.tax_check, name="tax_check"),
    path("pricing/download/", views.download_pricing_workbook, name="download_pricing_workbook"),
    path("pricing/upload/", views.upload_pricing_workbook, name="upload_pricing_workbook"),
    path("final-prices/<str:sku_id>/", views.final_price_detail, name="final_price_detail"),
    path("upload-orders/", views.upload_orders_csv, name="upload_orders"),
    path("full-orders/", views.full_orders_list, name="full_orders_list"),
    path("full-orders/analytics/", views.full_orders_analytics, name="full_orders_analytics"),
    path("dashboard/", views.dashboard_analytics, name="dashboard_analytics"),
    path("labels/parse/",            views.upload_labels_pdf,         name="upload_labels_pdf"),
    path("labels/orders/",           views.label_orders_list,         name="label_orders_list"),
    path("labels/summary/",          views.label_couriers_summary,    name="label_couriers_summary"),
    path("labels/duplicates/",       views.label_duplicate_customers, name="label_duplicate_customers"),
    path("labels/customer-history/", views.label_customer_history,    name="label_customer_history"),
    path("labels/customers/",        views.label_customers,           name="label_customers"),
    # Fraud & Blocked Customers
    path("fraud-customers/",                  views.fraud_customers,          name="fraud_customers"),
    path("blocked-customers/",                views.blocked_customers_list,   name="blocked_customers_list"),
    path("blocked-customers/<int:bc_id>/",    views.blocked_customer_detail,  name="blocked_customer_detail"),
    # Purchases & Inventory
    path("purchases/",              views.purchases_list,      name="purchases_list"),
    path("purchases/<int:bill_id>/",     views.purchase_detail, name="purchase_detail"),
    path("purchases/<int:bill_id>/pdf/", views.purchase_pdf,    name="purchase_pdf"),
    path("purchases/sku-items/",    views.purchase_sku_items,   name="purchase_sku_items"),
    path("purchases/sku-monthly/",  views.purchase_sku_monthly, name="purchase_sku_monthly"),
    path("purchases/items/<int:item_id>/", views.purchase_item_detail, name="purchase_item_detail"),
    path("inventory/",              views.inventory_view,           name="inventory_view"),
    path("inventory/new-sku/",      views.inventory_create_sku,     name="inventory_create_sku"),
    path("inventory/charts/",       views.inventory_charts,          name="inventory_charts"),
    path("inventory/logs/",         views.inventory_logs_list,       name="inventory_logs_list"),
    path("inventory/adjustments/",  views.inventory_adjustment_list, name="inventory_adjustment_list"),
    path("inventory/adjustments/<int:adj_id>/", views.inventory_adjustment_detail, name="inventory_adjustment_detail"),
    path("inventory/labels/",       views.inventory_labels_list,     name="inventory_labels_list"),
    path("inventory/packed/",       views.packed_stock_list,         name="packed_stock_list"),
    path("inventory/packed/<int:event_id>/", views.packed_stock_detail, name="packed_stock_detail"),
    path("inventory/<str:sku_id>/", views.inventory_delete_sku,      name="inventory_delete_sku"),
    path("consumables/items/",          views.consumable_items_list,       name="consumable_items_list"),
    path("consumables/items/<int:item_id>/", views.consumable_item_detail, name="consumable_item_detail"),
    path("consumables/purchases/",      views.consumable_purchases_list,   name="consumable_purchases_list"),
    path("consumables/purchases/<int:purchase_id>/", views.consumable_purchase_detail, name="consumable_purchase_detail"),
    path("consumables/usages/",         views.consumable_usages_list,      name="consumable_usages_list"),
    path("consumables/usages/<int:usage_id>/", views.consumable_usage_detail, name="consumable_usage_detail"),
    # Expenses: invoices (packaging / other) + daily transport charges
    path("expenses/invoices/",              views.expense_invoices_list,  name="expense_invoices_list"),
    path("expenses/invoices/<int:invoice_id>/", views.expense_invoice_detail, name="expense_invoice_detail"),
    path("expenses/transport/",             views.transport_charges_list, name="transport_charges_list"),
    path("expenses/transport/<int:charge_id>/", views.transport_charge_detail, name="transport_charge_detail"),
    path("expenses/summary/",               views.expenses_summary,       name="expenses_summary"),
    path("expenses/export/",                views.expenses_export,        name="expenses_export"),
    path("expenses/import/",                views.expenses_import,        name="expenses_import"),
    # Product Photography AI
    path("product-photos/generate/", views.generate_product_images, name="generate_product_images"),
    # Meesho Inventory
    path("meesho-inventory/",          views.meesho_inventory_list,     name="meesho_inventory_list"),
    path("meesho-inventory/upload/",   views.meesho_inventory_upload,   name="meesho_inventory_upload"),
    path("meesho-inventory/download/", views.meesho_inventory_download, name="meesho_inventory_download"),
    # Meesho Price Update
    path("meesho-price-update/",          views.meesho_price_update_list,     name="meesho_price_update_list"),
    path("meesho-price-update/download/", views.meesho_price_update_download, name="meesho_price_update_download"),
    # Return deliveries (returns received back) + 7-day claim tracking
    path("returns/",                    views.return_deliveries_list,   name="return_deliveries_list"),
    path("returns/upload/",             views.return_deliveries_upload, name="return_deliveries_upload"),
    path("returns/lookup/",             views.return_delivery_lookup,   name="return_delivery_lookup"),
    path("returns/<int:pk>/",           views.return_delivery_detail,   name="return_delivery_detail"),
    # Order scanning — log outgoing parcels at the desk and track their status
    path("order-scan/",              views.scanned_orders_list,        name="scanned_orders_list"),
    path("order-scan/bulk-status/",  views.scanned_orders_bulk_status, name="scanned_orders_bulk_status"),
    path("order-scan/<int:pk>/",     views.scanned_order_detail,       name="scanned_order_detail"),
    # Listing templates — synced from the Meesho browser extension
    path("listing-templates/",         views.listing_templates_list,   name="listing_templates_list"),
    path("listing-templates/import/",  views.listing_templates_import, name="listing_templates_import"),
    path("listing-templates/export/",  views.listing_templates_export, name="listing_templates_export"),
    path("listing-templates/<int:pk>/", views.listing_template_detail, name="listing_template_detail"),
    # GST — monthly liability from Meesho TCS exports
    path("gst/upload/",      views.gst_upload,      name="gst_upload"),
    path("gst/periods/",     views.gst_periods,     name="gst_periods"),
    path("gst/summary/",     views.gst_summary,     name="gst_summary"),
    path("gst/mismatches/",  views.gst_mismatches,  name="gst_mismatches"),
    # Label packing
    path("labels/orders/<str:order_id>/pack/", views.label_order_pack, name="label_order_pack"),
    path("labels/bulk-pack/",       views.label_bulk_pack,     name="label_bulk_pack"),
    path("labels/unpacked/",        views.label_unpacked,      name="label_unpacked"),
]
